openapi: 3.0.3
info:
  title: LCBO Stats Api
  description: LCBO Stats Api
  version: 0.0.1
servers:
  - url: 'lcbostats.com'
paths:
  /api/alcohol:
    get:
      summary: Returns a list of alcohols, sorted by price index.
      responses:
        '200':
          description: A JSON array of alcohols.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 69
                  created_at:
                    type: string
                    example: null
                  updated_at:
                    type: string
                    example: null
                  title:
                    type: string
                    example: Boxer Ice
                  brand:
                    type: string
                    example: Kelly's Inc.
                  category:
                    type: string
                    example: Spirits
                  subcategory:
                    type: string
                    example: Gin
                  price:
                    type: number
                    example: 9.99
                  volume:
                    type: integer
                    example: 750
                  alcohol_content:
                    type: number
                    example: 40
                  price_index:
                    type: number
                    example: 0.075
                    description: The cost of one ml of one part alcohol (1ml 100% alcohol)
                  country:
                    type: string
                    example: Canada
                  url:
                    type: string
                    example: www.lcbo.com/item
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: false
          description: A specific ID for an alcohol.
          example: 1

        - in: query
          name: title
          schema:
            type: string
          required: false
          description: A specific title for an alcohol.
          example: Kelly's

        - in: query
          name: brand
          schema:
            type: string
          required: false
          description: A specific brand for an alcohol.
          example: Crown Royal Incorporated

        - in: query
          name: category
          schema:
            type: string
          required: false
          description: A specific category of alcohol.
          example: Spirits

        - in: query
          name: subcategory
          schema:
            type: string
          required: false
          description: A specific subcategory (i.e. Beer --> Lager, Spirits --> Gin) of alcohol.
          example: Lager

        - in: query
          name: country
          schema:
            type: string
          required: false
          description: A specific country of origin for an alcohol.
          example: Canada

        - in: query
          name: sortBy
          schema:
            type: string
          required: false
          description: A value that determines what field the returned results are sorted by.
          example: price_index

        - in: query
          name: order
          schema:
            type: string
          required: false
          description: A value that determines what order, ascending or descending, the returned results are sorted by.
          example: asc || desc

        - in: query
          name: numberOfResults
          schema:
            type: integer
          required: false
          description: A value that determines the number of results to be returned. Max value of 100 is enforced.
          example: 69

        - in: query
          name: maxPriceIndex
          schema:
            type: number
          required: false
          description: The maximum price index of alcohols that will be returned.
          example: 0.09

        - in: query
          name: minPriceIndex
          schema:
            type: number
          required: false
          description: The minimum price index of alcohols that will be returned.
          example: 0.07

        - in: query
          name: maxPrice
          schema:
            type: number
          required: false
          description: The maximum price of alcohols that will be returned.
          example: 39.99

        - in: query
          name: minPrice
          schema:
            type: number
          required: false
          description: The minimum price of alcohols that will be returned
          example: 19.99

        - in: query
          name: maxVolume
          schema:
            type: number
          required: false
          description: The maximum unit volume of alcohols that will be returned.
          example: 750

        - in: query
          name: minVolume
          schema:
            type: number
          required: false
          description: The minimum unit volume of alcohols that will be returned.
          example: 375

        - in: query
          name: maxAlcoholContent
          schema:
            type: number
          required: false
          description: The minimum alcohol content of alcohols that will be returned.
          example: 76

        - in: query
          name: minAlcoholContent
          schema:
            type: number
          required: false
          description: The minimum alcohol content of alcohols that will be returned.
          example: 20

  /api/alcohol/efficient:
    get:
      summary: Returns a list of alcohols, sorted by price index.
      parameters:
        - in: query
          name: minPriceIndex
          schema:
            type: number
          required: false
          description: The lowest price index value that will be returned when searching for efficient alcohol.
          example: 0.07

        - in: query
          name: maxPriceIndex
          schema:
            type: number
          required: false
          description: The highest price index value that will be returned when searching for efficient alcohol.
          example: 0.09

      responses:
        '200':
          description: A JSON array of alcohols, sorted by price index.

          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: don't know lol
                    example: 69
                  created_at:
                    type: string
                    example: null
                  updated_at:
                    type: string
                    example: null
                  title:
                    type: string
                    example: Boxer Ice
                  brand:
                    type: string
                    example: Kelly's Inc.
                  category:
                    type: string
                    example: Spirits
                  subcategory:
                    type: string
                    example: Gin
                  price:
                    type: number
                    example: 9.99
                  volume:
                    type: integer
                    example: 750
                  alcohol_content:
                    type: number
                    example: 40
                  price_index:
                    type: number
                    example: 0.075
                    description: The cost of one ml of one part alcohol (1ml 100% alcohol)
                  country:
                    type: string
                    example: Canada
                  url:
                    type: string
                    example: www.lcbo.com/item

